Test Proxy Agent (#4335)
* test proxy agent

* canary branch parameter

diff --git a/.azure-pipelines/pipeline.yml b/.azure-pipelines/pipeline.yml
--- a/.azure-pipelines/pipeline.yml
+++ b/.azure-pipelines/pipeline.yml
@@ -29,6 +29,9 @@ parameters:
 - name: releaseRhelOnly
   type: boolean
   default: false
+- name: testProxyAgent
+  type: boolean
+  default: false
 
 # Targets
 - name: win_x64
@@ -72,6 +75,43 @@ stages:
 - stage: build
   displayName: Build
   jobs:
+  # Test Proxy Agent
+  - ${{ if parameters.testProxyAgent }}:
+    - job: test_proxy_agent
+      displayName: Test Proxy Agent
+      pool:
+        vmImage: ubuntu-latest
+      variables:
+        DisableDockerDetector: true
+        NugetSecurityAnalysisWarningLevel: none
+      steps:
+      - bash: |
+          cd ./.azure-pipelines/scripts/
+          npm install axios minimist
+
+          source="$(Build.SourceBranch)"
+          prefix="refs/heads/"
+
+          if [[ "${source}" == "${prefix}"* ]]; then
+              branch="${source#"${prefix}"}"
+
+              if [[ "${branch}" == "master" ]]; then
+                  branch="${{ parameters.branch }}"
+              fi
+
+              echo "Canary \"branch\" parameter: \"${branch}\""
+          else
+              echo "##vso[task.logissue type=error]This test is supported only if the build source branch name is specified directly"
+
+              exit 1
+          fi
+
+          node ./run-and-verify.js \
+              --projectUrl "$(CANARY_PROJECT_URL)" \
+              --pipelineId "$(CANARY_PIPELINE_ID)" \
+              --token "$(CANARY_PAT)" \
+              --templateParameters "{ \"branch\": \"${branch}\" }"
+        displayName: Test Proxy Agent
 
   # Windows (x64)
   - ${{ if and(parameters.win_x64, not(parameters.releaseRhelOnly)) }}:
